mysql:
  host: docker.for.mac.host.internal

spring:
  profiles:
    active: prod
  datasource:
    druid:
      username: well
      password: 123456
  redis:
    host: ${mysql.host}
    password: 123456
  zipkin:
    base-url: ${zipkin.list}
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: ${eureka.list}