spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.cloud.gateway: info
