mysql:
  host: 127.0.0.1

spring:
  profiles:
    active: dev

mybatis-plus:
  configuration:
    # 打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
