server:
  port: 9000
  use-forward-headers: true
  undertow:
    io-threads: 4
    buffer-size: 1024
    worker-threads: 20
    direct-buffers: true

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    suffix: .html
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: provider-user
          uri: lb://PROVIDER-USER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    status-page-url: http://127.0.0.1:${server.port}/
  client:
    registry-fetch-interval-seconds: 3
    instance-info-replication-interval-seconds: 3
    service-url:
      defaultZone: http://root:root@127.0.0.1:8001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS
